[build-system]
requires = ['setuptools>=75.0', 'wheel>=0.44']
build-backend = 'setuptools.build_meta'


[project]
name = 'jasmine_toolkit'
description = 'A tool suite for the development of JASMINE'
keywords = ['astronomy', 'JASMINE']
license = 'MIT'
license-files = ['LICENSE']

authors = [
  { name = 'Ryou Ohsawa', email = 'ryou.ohsawa@nao.ac.jp' }
]

classifiers = [
  'Development Status :: 3 - Alpha',
  'Intended Audience :: Science/Research',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.9',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Topic :: Scientific/Engineering :: Astronomy'
]

dynamic = ['version', 'readme']

dependencies = [
  'astropy>=7.0',
  'astroquery>0.4',
  'dust_extinction>=1.5',
  'matplotlib>=3.10',
  'numpy>=2.0',
  'pandas>=2.2',
  'poppy>=1.1',
  'scipy>=1.14',
  'synphot>1.4',
]


[project.optional-dependencies]
test = [
  'pytest>=8.3',
  'pytest-cov>=5.0',
  'pytest-forked>=1.6'
]


[project.scripts]
jasmine_toolkit = 'jasmine_toolkit.bin.toolkit:main'


[project.urls]
homepage = 'https://github.com/JASMINE-Mission/jasmine_toolkit'
repository = 'https://github.com/JASMINE-Mission/jasmine_toolkit'


[tool.setuptools.packages.find]
include = ['jasmine_toolkit*']


[tool.setuptools.dynamic]
version = { attr = 'jasmine_toolkit.version.version' }
readme = { file = 'README.md', content-type = 'text/markdown' }


[tool.setuptools.package-data]
"jasmine_toolkit.resource" = [
  'filter/filter100.json',
  'qe/qe170.json',
  'telescope/teleff.json',
  'telescope/FringeZernike_2D-s1_jas36xm2.csv'
]

[tool.ruff]
exclude = ['**/test', 'notebook']
line-length = 79
indent-width = 4

[tool.ruff.lint]
select = [
  'E', 'F', 'W']
ignore = [
  'E221', # multiple spaces before operator
  'E401', # multiple imports on one line
  'E701', # multiple statements on one line
  'E731', # Do not assign a `lambda` expression
  'E741', # Ambiguous variable name
  'F403', # star imports
  'F405', # defined from star imports
]
unfixable = ['ALL']

[tool.ruff.format]
quote-style = 'preserve'
line-ending = 'lf'
preview = true
