name: unittest
description: Unittest

runs:
  using: composite
  steps:
    - name: Install package
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        python -m pip install .[test]
      shell: bash

    - name: Test with pytest
      env:
        BRANCH: ${{ github.ref_name }}
      id: pytest
      continue-on-error: true
      run: |
        python -m pytest -v --forked jasmine_toolkit --cov=jasmine_toolkit --cov-report xml
      shell: bash

    - name: Send Coverage Report to qlty.cloud
      uses: qltysh/qlty-action/coverage@v1
      with:
        token: ${{ env.QLTY_COVERAGE_TOKEN }}
        files: coverage.xml
        add-prefix: jasmine_toolkit/

    - name: Notice Error
      if: ${{ steps.pytest.outcome == 'failure' }}
      run: exit 1
      shell: bash
