import numpy as np
from numpy.ma import copy


class PointingPlan:
    def __init__(self):
        self.__pointing_entries: np.ndarray = np.array([])

    def add_entry(self, entry: np.ndarray) -> np.ndarray:
        self.__pointing_entries = np.vstack(self.__pointing_entries, entry)

    def get_array(self) -> np.ndarray:
        # TODO
        #   This code is dangerous. copy function of numpy.ndarray automatically select deep or shallow copy, and is
        #   not controllable by user.  Return value should be a new object generated by deep copy. Some instruction
        #   show that use copy.deepcopy(ndarray) but error occurs.  Need to find appropriate method.
        return self.__pointing_entries.copy()
