name: validation
description: Detailed test for code validation.

runs:
  using: "composite"
  steps:
    - name: Install package
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        python -m pip install .[test]
      shell: bash

    - name: Code validation
      env:
        BRANCH: ${{ github.ref_name }}
      id: pytest
      continue-on-error: true
      run: |
        python -m pytest validation --cov=. --cov-report xml
      shell: bash

    - name: Send Coverage Report to CodeClimate
      if: ${{ steps.pytest.outcome == 'success' && github.event_name == 'push'}}
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ env.CC_TEST_REPORTER_ID }}
      with:
        debug: false
        coverageLocations: coverage.xml:coverage.py

    - name: Notice Slack
      if: ${{ steps.pytest.outcome == 'failure' }}
      uses: slackapi/slack-github-action@v1.21.0
      with:
        payload: |
          {
            "text": "some test in ${{ env.TEST_DIR }} failed in ${{ github.ref_name }}. Please checK the details in the corresponding errors in Actions in Github."
          }
      env:
        SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL}}

    - name: Notice Error
      if: ${{ steps.pytest.outcome == 'failure' }}
      run: exit 1
      shell: bash
